import type { Photo, PhotoManifest } from '@/types/photo';

/**
 * Generated by `npm run upload-photos`. Each entry holds intrinsic dimensions
 * and (optionally) a per-photo URL override. URLs are otherwise computed from
 * the photo id by `getPhotoUrl()`.
 *
 * Until the upload script runs, this is empty and hallways render placeholder
 * frames. That's intentional — the game must work without photos for dev.
 */
export const PHOTO_MANIFEST: PhotoManifest = {
  // example entry, kept as documentation:
  // 'europe/01-paris-rooftop': { id: 'europe/01-paris-rooftop', width: 1920, height: 1280 },
};

const BLOB_BASE = (import.meta.env.VITE_BLOB_BASE as string | undefined) ?? '';

const getPhotoUrl = (id: string, variant: 'thumb' | 'full'): string => {
  const safeId = id.replace(/\//g, '_');
  return `${BLOB_BASE}/${safeId}-${variant}.webp`;
};

export const resolvePhoto = (id: string): Photo | null => {
  const meta = PHOTO_MANIFEST[id];
  if (!meta) return null;
  return {
    id,
    width: meta.width,
    height: meta.height,
    thumbUrl: getPhotoUrl(id, 'thumb'),
    fullUrl: getPhotoUrl(id, 'full'),
  };
};

export const allPhotoIds = (): string[] => Object.keys(PHOTO_MANIFEST);

export const photoIdsForGallery = (gallery: string): string[] =>
  allPhotoIds().filter((id) => id.startsWith(`${gallery}/`));
